//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DibumiLaptopWEBV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.item_stok = new HashSet<item_stok>();
            this.return_item = new HashSet<return_item>();
            this.transaksis = new HashSet<transaksi>();
        }
    
        public long id { get; set; }
        public Nullable<long> merek_id { get; set; }
        public string tipe { get; set; }
        public string deskripsi { get; set; }
        public string processor { get; set; }
        public string ram { get; set; }
        public string penyimpanan { get; set; }
        public string ukuran_layar { get; set; }
        public Nullable<long> stok { get; set; }
        public Nullable<long> gudang_id { get; set; }
        public Nullable<long> kondisi_id { get; set; }
        public Nullable<System.DateTime> tanggal_ditambahkan { get; set; }
        public Nullable<long> garansi_id { get; set; }
        public Nullable<System.DateTime> garansi_expired { get; set; }
        public Nullable<long> harga { get; set; }
    
        public virtual garansi garansi { get; set; }
        public virtual gudang gudang { get; set; }
        public virtual kondisi kondisi { get; set; }
        public virtual merek merek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_stok> item_stok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<return_item> return_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi> transaksis { get; set; }
    }
}
