//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DibumiLaptopWEBV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaksi()
        {
            this.return_item = new HashSet<return_item>();
        }
    
        public long id { get; set; }
        public Nullable<long> item_id { get; set; }
        public Nullable<System.DateTime> tanggal_transaksi { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<long> harga_satuan_temp { get; set; }
        public Nullable<long> total_harga { get; set; }
        public string deskripsi { get; set; }
    
        public virtual item item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<return_item> return_item { get; set; }
    }
}
